version: '3.8'

services:
  zookeeper:
    image: bitnami/zookeeper:3.8.0
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ALLOW_ANONYMOUS_LOGIN: "yes"
    volumes:
      - zookeeper_data:/bitnami/zookeeper
      - zookeeper_datalog:/bitnami/zookeeper/data

  kafka:
    image: bitnami/kafka:3.2.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - kafka_data:/bitnami/kafka
    depends_on:
      - zookeeper

  app:
    build: .
    ports:
      - "8000:8000"
    command: sh -c "wait-for-it.sh kafka:9092 -- wait-for-it.sh db:5432 -- uvicorn app.main:app --host 0.0.0.0 --port 8000"
    depends_on:
      - kafka
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  zookeeper_data: {}
  zookeeper_datalog: {}
  kafka_data: {}
  pgdata: {}
